### PR TITLE
Update product metadata and Auxiliary files.

### PR DESCRIPTION
**Pull request by glaubervila**
A new page was implemented for editing already registered products.
It is possible to change the description and change the auxiliary files.

To change a file, you must remove the old one and upload it again.

Creation and update dates have also been added to both the product metadata and each file.

I did not implement error handling. After testing, a new task may be necessary to handle error messages.

### CODE REVIEW

**Review by jandsonrj — APPROVED** [review]
I did the tests in my local environment and everything worked fine.tI did the tests in my local environment and everything worked fine.

**Review by gschwend — CHANGES_REQUESTED** [review]
- [ ] Please change the update button to become more visible
- [ ] add a new button "Done" an the bottom to go back to the previous page (user_products or oficial products)

**Comment by gschwend** [comment]
> * [ ]  Please change the update button to become more visible
> * [ ]  exit edit screen after submit the update

@jandsonrj

**Comment by gschwend** [comment]
image
Suggestion

**Review by gschwend — APPROVED** [review]

**Pull request merged**
